image:
  file: .gitpod.Dockerfile

tasks:
  - name: run
    before: |
      yugabyted start --base_dir=$STORE --listen=$HOST_LB --tserver_webserver_port=$TSERVER_WEBSERVER_PORT
    command: |
      gp await-port 5433
      ysqlsh
# exposed ports
ports:
  - port: 7000
    onOpen: notify
  - port: 8200
    onOpen: notify
  - port: 37843
    onOpen: ignore
  - port: 7100
    onOpen: ignore
  - port: 9100
    onOpen: ignore
  - port: 5433
    onOpen: notify
  - port: 13000
    onOpen: ignore
  - port: 9042
    onOpen: notify
  - port: 12000
    onOpen: ignore

vscode:
  extensions:
    - GitHub.vscode-pull-request-github
    - https://open-vsx.org/api/ms-python/python/2022.10.0/file/ms-python.python-2022.10.0.vsix
    - https://open-vsx.org/api/ms-toolsai/jupyter/2022.7.1001890528/file/ms-toolsai.jupyter-2022.7.1001890528.vsix